name: magritte
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - readline
  - ca-certificates
  - openssl
  - pandas
  - numpy
  - xlrd
  - chardet
  - matplotlib
  - scikit-learn
  - seaborn
  - regex
  -  pip:
      - torch
      - torchtext
      - torchvision
      - lightning
      - transformers=4.30

